language: c

compiler:
  - gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install cmake libsdl1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libxml2-dev
  - mkdir build
  - cd build
  - cmake ..

script: make
