CFLAGS = -Wall -O2 -g
SDLCONFIG = sdl-config
CURLCONFIG = curl-config
LIBS = -lSDL_image -lSDL_gfx -lSDL_ttf

pspmaps: pspmaps.c
	$(CC) $(CFLAGS) -o pspmaps pspmaps.c $(LIBS) `$(CURLCONFIG) --cflags --libs` `$(SDLCONFIG) --cflags --libs`

clean:
	rm -f pspmaps
